apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-imaginary
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Team Imaginary Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: imaginary-*
    server: https://kubernetes.default.svc
